Token: '***insertTokenHere***'
URL: 'https://pastebin.com/raw/zYBsBi5R'
Split: '>>'
Ops:
  - '145436402107154433'
BarredUsers:
  - null
DefaultChannelType: 'quiet'
LoudChannels:
  - 'help-desk'
  - 'development'
QuietChannels:
  - 'general'
  - 'suggestions'
  - 'server'
IgnoredChannels:
  - 'off-topic'
  - 'staff'
  - 'politics'
  - 'gaming'
  - 'announcements'